### PR TITLE
Keep the old decrypt process for migration purposes

### PR DESCRIPTION
**Pull request by dmathieu**
See the README.md file for migration steps.

@neilmiddleton: this should fit your migration.

### CODE REVIEW

**Comment by neilmiddleton** [comment]
Looks good to me.

What would be real nice is a message output on `bundle install` stating that the migration to the new scheme is very much required.

**Comment by dmathieu** [comment]
Done! :sunglasses:

**Comment by neilmiddleton** [comment]
Awesome.  I'm tempted to hold off on merging this until Fernet 2.0.0 is a thing tho to save re-bumping it later (and avoiding any potential data destroying bugs in the RC).

**Comment by dmathieu** [comment]
Fine by me.

**Pull request closed without merging**
